name: Tests

on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies 
        run : |
          sudo apt-get update
          sudo apt-get install -y clang ninja-build cmake doctest-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build tests
        run: |
          cmake -B build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release \
            -DMAYAK_LOGGER_BUILD_EXAMPLES=ON -DMAYAK_LOGGER_BUILD_TESTS=ON -DMAYAK_LOGGER_GENERATE_DOCS=ON
          cmake --build build

      - name: Run tests
        run: build/tests
